#Tell Travis we need a copy of docker running
#
sudo: required
services:
  - docker

#Build our image using Dockerfile.dev
#
before _install:
  - docker build -t sddelaney/docker-react -f Dockerfile.dev .


#Tell travis how to run the test suite
#
script:
  - docker run -e CI=true sddelaney/docker-react npm run test

#Tell travis how to deploy our code to AWS
#
deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-474760663277"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
