#Tell Travis we need a copy of docker running
#
sudo: required
services:
  - docker

#Build our image using Dockerfile.dev
#
before _install:
  - docker build -t sddelaney/docker-react -f Dockerfile.dev .


#Tell travis how to run the test suite
#
script:
  - docker run -e CI=true sddelaney/docker-react npm run test

#Tell travis how to deploy our code to AWS
#

